apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec: 
  containers:
  - name: nginx
    image: nginx:perl
    ports:
    - containerPort: 80
      protocol: TCP

  - name: debian
    image: debian:latest
    command: ["sleep", "2000"]