apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec: 
  containers:
  - name: nginx
    image: nginx:perl

  - name: busybox
    image: busybox:latest
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3700'] 
    ports:
    - containerPort: 90
      protocol: TCP
--- 

apiVersion: v1
kind: Pod
metadata:
  name: simplepod
spec:
  containers:
  - name: httpd
    image: httpd:latest
    ports:
    - containerPort: 80
      protocol: TCP