apiVersion: v1
kind: Pod
metadata:
  name: nginx-env
spec:
  containers:
  - name: nginx
    image: nginx:perl 
    env:
    - name: APP
      value: "expense"
    - name: VERSION
      value: "15"
    - name: TEAM
      value: "Simbaa"

 