apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
data:
  db_user: "eWFzaHZhbnRoCg==" 
  db_password: "cGFzc3dvcmQK"
  .secret_file: "c2FtcC5zZWMudHh0Cg=="
--- 
apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec:
  containers:
  - name: nginx
    image: nginx:perl 
    envFrom:
    - secretRef:
        name: nginx-secret