apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:otel
        ports:
        - containerPort: 80

# Deployment set is a higher-level abstraction that manages a set of replicas of a pod.
# - It provides declarative updates to the pods and ReplicaSets.
# - It allows you to define the desired state of the application, and Kubernetes will automatically manage the deployment to achieve that state.
# This allows updates to be rolled out gradually, with the ability to roll back to a previous version if needed.
# You can udpate the pods by using RollingUpdate or by Recreate strategy.